---
- name: remove nmap
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: remove nmap
      apt:
        name: nmap
        state: absent
      ignore_errors: true
    - name: update repo
      apt:
        update_cache: true
    - name: install nmap
      apt:
        name: nmap
        state: latest      
  