---

- name: run command dbendon username
  hosts: all
  become: true
  tasks:
    - name: intall tmux in debian 
      apt:
        name: tmux
        state: latest
      when: ansible_facts['user_id'] == "root"


# when you get varuble from inventory file
# when: ansible_user == "root"

#when you get varuble from gather_facts module
#when: ansible_facts['user_id'] == "root"