---

- name: start apache2 service
  service:
    name: apache2
    state: started
    #enable: ture


- name:  copy main.php to /var/www/html
  copy:
    src: main.php
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
    

